---
# Name: Install and configure our controller

- name: Install essential utils
  apt: 
    name:
      - openssh-server
      - nano
      - joe
      - git
      - screen
      - tmux
      - molly-guard
      - htop
    state: latest

- name: Install KeePass
  apt: name=keepass2 state=latest
