---
# file: controller.yml

# This playbook is intended to set up some initial
# services and goodies on a brand new Controller host.

- hosts: controller
  remote_user: 'wings'
  vars_files:
    - "vars/controller.yml"
  become: yes

  roles:
  - controller
  - { role: controller_awx,
    when: deploy_awx == true }
